### ISSUE TITLE
Update cabal package on Hackage

### ISSUE THREAD

**Issue by Zimmi48** [TomMD/gps#3]
Hi,

I've been using your library and I've had problems with the interpolate function until the point where I realized that it was addVector whose code was incorrect but you have corrected it in the last version.
The only problem is that gps-1.1 is still the last version available on Hackage. That would be good if you updated it.

Meanwhile, I've copied your code into my project as a temporary fix.

Thanks !

**Comment by TomMD** [comment]
What?   A user?  Neat!   I'll push and hopefully find time to make actual unit tests so these sorts of things don't make it to hackage in the first place.  Thanks for the report.

**Comment by TomMD** [comment]
Uploaded as version 1.2
